auth:
    local:
        allowedOrigins:
            - ENC[AES256_GCM,data:jC3/Jv7PEmW6Zv0fRsQHIExKHhrTorK7,iv:Ar0/CxT1XuxYUBsdXoLtXuqD0/cTmXyW+poYoPTA5QU=,tag:BweK5n8+zpVvSweR/n9G6w==,type:str]
        defaultRedirectOrigin: ENC[AES256_GCM,data:mO6Ktfe5qUMMbbg1FJAh5ikluQq1w/ax,iv:ummH0uiUKHWAGcrqnLxyYB9IHXEqUSj7Zi08soNldFU=,tag:mvWOt9bCgcFHkSt7w+ZHBw==,type:str]
        redirectPath: ENC[AES256_GCM,data:0xsqxpXc5h7xAFM6,iv:dgXcMtQlHfqWsAb+gLWkxbCc693UypZTJalblm1Kqls=,tag:NTZm/XfVORfB/N7+nK0qsw==,type:str]
        line:
            channelID: ENC[AES256_GCM,data:f/NI6kWKwf4IDnhx0kw2s/ucxfM=,iv:E3pfNpKbF7sDJoV53RUOZrkDibALVsrxkfG8UVNb0nU=,tag:jEpjQ8Lr7uDMeVR8gv7UbQ==,type:str]
            channelSecret: ENC[AES256_GCM,data:kXrMd7/j3j8qqIrXoIe0I7r6Ng==,iv:IXf6Dun2YgRStuz1oQIYRJBc5+Cx7VQTPWbH7/WW2lo=,tag:d6M93LRh9AdpJP1fewn3VQ==,type:str]
            redirectURI: ENC[AES256_GCM,data:VBmeGN0gEac5+bRkcn7GEfaAkAV/gu2pzGpaPDKTgMgjJY91xsYi0ic+Kw==,iv:X9pgbDsayrFC468a2omgV8qngLWDbpyXt3V2BHEKh6w=,tag:fejB+qB7a7o3C6RKkx93zg==,type:str]
            scopes:
                - ENC[AES256_GCM,data:hKjI/NyaSg==,iv:8vHzhmqX64HG+slnVSmPA3EYBUxZhSSx0lRcEuqzjhU=,tag:o+JB+9tu5pLQu1y4nLiK1Q==,type:str]
                - ENC[AES256_GCM,data:U80eEjKp,iv:dZZnRx4XILCg58ADqvYcCkkD325QVoxqT3Rx+ZTpdfo=,tag:L3vCiuvtdP1QG3Y3o2e0iw==,type:str]
            stateSecret: ENC[AES256_GCM,data:WxKIpuhmankV2eGqqPv9X5Ze1PsHMk9tpQ==,iv:Q9CnnIt5cucEpmK1oxK6o47mi621UN/cFerxW0NmT7w=,tag:GmCjIY8jkiKL8r4YFwvLxQ==,type:str]
            stateTTL: ENC[AES256_GCM,data:FTS3,iv:AABgdXgiDlZlg8MRAObJtyc9KRAMgxLR9L38Qgw8m5s=,tag:QecyHkM6TcYaUpNPZIwNFA==,type:str]
            jwtSecret: ENC[AES256_GCM,data:layaNP6Rsp6DVmxBRhFt9gh4KSgwJDk=,iv:nX3QnbonDruQ1A+Bu/LZFulIxv8F5ddEHrTBt5Q7wIY=,tag:0zQhb9Ng8tvsmcjV6fz59Q==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:mfB99E21RALN,iv:iGOGgk5G10uJao9CyS1hYAQ1W8i5lpoTSKUGasCo8v0=,tag:3YllBsiPUw43n6VO6KqwRQ==,type:str]
            jwtAudience: ENC[AES256_GCM,data:NXb7JzUP394=,iv:GENNsXUGozmKu0tWEd5F8TVDon8Ekek1XsnAn6/c340=,tag:kpWmo+aAxflLsucRyah/1g==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:LZ4D,iv:o6jFj23RcKMLaDPeLdBMlkZrBjATQYUtdF/+9LB7Icc=,tag:XqdWIQncXSmup0l614AZlQ==,type:str]
        twitter:
            clientID: ENC[AES256_GCM,data:sZh3WChkMEadc3urOyRDyK7kv4QjXA==,iv:Jd65LBJOETRWgujat/fMxBkbckJDfJrFyN24UlxyWIc=,tag:VsQpfdQ/atRe4FGURzifeQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:olPocK+wETTxlGyqisdDBahHFRJOhA==,iv:eJgmLwbnRCa+p/pYpZ40VxlMbdsPUOUjibHXWUlDk7Q=,tag:BNPOYs2yU4bzHHRTc839iQ==,type:str]
            redirectURI: ENC[AES256_GCM,data:zNsp7P8QJyAOrU7wyuif5fK+17s6miRxS63Wi0hyN/Bs+Zc10D5lddRfE+4ifQ==,iv:P2eXk16IFu4xtJPnPdog4UbMb0vtSIaMbZrb31WfMo0=,tag:5q6huc6k4czvaNNmkd22Gg==,type:str]
            scopes:
                - ENC[AES256_GCM,data:siZwK2Z6T+S2HA==,iv:2sAhXEazW3wVFDkkE8m6vyjk9b2JfAyH1rDQgo8tz2E=,tag:qKDRCBZ13ZAdXl6+Eqy9TA==,type:str]
                - ENC[AES256_GCM,data:g9PD3zE4Ue2MzQ==,iv:Gi9M8uUZq5RR+DI8tblKkfsAodh224akAzY1cbMt35Q=,tag:YtvotLd326k3znDdgPkDLA==,type:str]
                - ENC[AES256_GCM,data:+s3MiOb2nkdtzkGNzJA=,iv:TekGp+KWNd0MxfrVN8NSSzYJCRrnWQLWEBxqCd2DLe0=,tag:RzpTkEgi4wDz1vf3C0OTew==,type:str]
            stateSecret: ENC[AES256_GCM,data:mo0xXLs2l80GuPzXpr9jbIfYktN7uCvVjwXIww==,iv:+KDD+c7MifpQFwTcC1ljc/iBpixYy5lIzNqhmxWdD+g=,tag:tJf3I5JnHGFG5TBevWIc6Q==,type:str]
            stateTTL: ENC[AES256_GCM,data:pJXy,iv:xKFTb3Aor0s506JUvvfUWG8gRxPqwV4Hn4AyuTGTn0s=,tag:RiKwokl6PlyHrm3SNj55ZA==,type:str]
            jwtSecret: ENC[AES256_GCM,data:9nUKU4wuUDOd7Kc6RWefgXsni9v7AVrUyJo=,iv:dBijuh6Fp1euKxPj2VPAd/+cd69YggMe7ZqC5xQTj7o=,tag:kP5kCa/MkrTW4doe1Ga0iQ==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:1fGfB1YwhRR93Pc6,iv:lrldX9Sss+KC/YGDm7iVGgY0wqLgSK1cNXpYcaPmX30=,tag:6g7Vr8xOKisgsRjd1zVVAg==,type:str]
            jwtAudience: ENC[AES256_GCM,data:7ZCdCiSpdIs=,iv:2XMmLJorCmtCIgIc/NyhlaqbfzKPR/9ypINyWst+8qA=,tag:7AjW/6mInnCvorEXkiOMVA==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:L+92,iv:nlw73BJy+udjfTuKByOUYVgxHAV5MHk/S5cpKHjdC4g=,tag:gUEtdU+NsGGnMTG22OnZYA==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb21QK3g5SzBNbzhsMGhw
            OHhzMUxFTHpOdnJsRTNaRHlIaTJHc05WQkNvCldBcFlmU09TQjc0eWUxV0RUQUl3
            Y0NYeFo1SGw4dVRISWRUdkJ0R1dVeVUKLS0tIDBvQjZTUkNFOFFxVHlLaEZoSUE1
            b3lBLzROREVoZVJ1QjNGS3c3VnJvTmMKaqMYhf0sjsuI1kVgHI3KILR9GsyARnsW
            nCm3K3tVH66WdBO2x7YKRb5dH8RsawSb40drZpLqSAE04G8c03GAjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:35:25Z"
    mac: ENC[AES256_GCM,data:rYyWGADApUF8oVxog+Fncow0Jv1pO3CPfb74ejZ7RxoQEM7fbpXdk+VmqyOHIa22NH2ocmvl09HLxB70euy/Bf6byBzTWn8ANnqiJfebtQWpiempOfv6jvykGJPLSs/SF/XgdrG3UOOfFmHC3F0w1WqCXvvlZHeMDBQY29b8mRA=,iv:CPxIiiNzSvQ6L3DhY0A6z7eK1jqmVo0oQP5z51OYRkQ=,tag:3YdThsd4E1M9pMuCMqFfjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
