message:
    makotoclub:
        natsURL: ENC[AES256_GCM,data:iHY5t4zkX6CLZrL6iRy3QA==,iv:InKx9swj4q18Tl7MU2EbYqGBO4rAyczn7sPsUpFNkXY=,tag:ZPY/hWxcL5dOx/3AGeolVA==,type:str]
        lineSubject: ENC[AES256_GCM,data:e84Oawm9pgJdSxeN/hYg9wVvf+us0Q==,iv:yGXfDKEynXO8r9qmW6t9rOCl8yn8uqft4/bWZXZyLog=,tag:t9SfoechKJLxKqNDE4pJcA==,type:str]
        discordSubject: ENC[AES256_GCM,data:cJslXRsY76WI7wvsrMGAOOcJiNPMxMFzAkIR,iv:vhgvip7HOc/pO4v/Pi1v/H+kPrbJEYEBFivSEpuvyJ8=,tag:pFBTwkj7qAVsyjsyJf9+Zg==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:/beS/pkFwlHmFvESNNCeMO/FFvk5zE29yeQRKRo5tMiqHANm2Ewh,iv:wnSrrN4RFQxJHhmCyKtffAqr4TJ34XWP3fUjvGrlm6Y=,tag:8+ZErbKtlkLTtTxxattZqQ==,type:str]
            channelToken: ENC[AES256_GCM,data:PP4AfXcFQQbGm/Mby2v/sw==,iv:xOB9/4sg8Nu/vpvH7HstuhTtEbOQOtejc+HNFEr7g3A=,tag:KVwGRH8FS7to+sDlFXEPoA==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:ahH5PvFVJf688ehpJdk12x40UkkHMNXKzxwA1Dm628sS9v5h47WqgUIoWOpQXoD4efsf3fZx38xlsh56dlxsBMhXKeGdutGFPrFgg+Kj3zklrhvFFfET9I0Xl/rabKX8mwA9sOywL6NV7TGjDVgtMwnUSgKvDVf1pg==,iv:K2yNyEIXWSY10e9bTeVc2vz4T5OqZ7k+NuJ/W/wUrho=,tag:qh4ZAP23xsDzaLrzyV65Yw==,type:str]
            username: ENC[AES256_GCM,data:5e7tMoVxJShU1oFPB5510Cqa,iv:jOGgs6ipDtzCcaYZJV/keXtrGEMfQln3f4vpf973Hck=,tag:fmE3bHDeMgcTgDw70Mvbnw==,type:str]
            avatarURL: ""
        defaultDestination: ENC[AES256_GCM,data:wEMr9xFIew==,iv:WiHv7v27Y+EWlzV2dSJ90QZs8kzNLctcCWIV9pVx6Ew=,tag:E2o3fFwDHhmpbMXpjn8mkQ==,type:str]
        ingressTimeout: ENC[AES256_GCM,data:8BU=,iv:06NQHeMDG8hXtlM0cv6iAnMTElW8wLPWkxjG9LcZflc=,tag:+3VfrR+t2a1wbMyU84dHEg==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:ys0=,iv:SpmJ2AO2cICOv9S437zgZdF6FqmVAk2EnrJnNguF28Y=,tag:plfXEaMwuOp32mQ+o68JXQ==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDejdSUExwaVhiMGpkSElR
            TjBBNHJ6Q1VxUm5kUkw5M1NkR0M3R0VGL0J3CkQvYU9INk9WWWxiRVdUdWE2bjdp
            ZERpNUU3dmJvTzhadEFZMm5lZktyZFkKLS0tIDFiV2EvT0p2SUFlWnlLNFBJUERL
            YkNlR1FkbWNZTmMwNTlOVUEwUkdTSXMKZk5JigGqelDqZNMyb34OY2c55JdB0bwd
            BSP4GjBPol3VJ8zLNXyJdWJqtr0nlpeJEESsnbxquZMSVwAW4IzzyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:35:25Z"
    mac: ENC[AES256_GCM,data:ZYKRsUY1P8wkntbD+f30GQJPld/X67wDPqRXtdUsbsJ4dFYVK2x4Bju1ZOBrYo7xZaN/9/BjqneLyh28QxEtyw/WT1OTsV+tCChOupil++g3QUq0nXTNpgf7tUzXdkk2iQhcYbKqjLSaIdOOesdI8jPcRrdy38N58q6Qdl3hzhE=,iv:aGi8tlYnjYMxooWACh7XnI6eDFg72MLu30ME6S4dUgA=,tag:8bVlYFmVkeHJLr6JkYs54w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
