message:
    sngm3741:
        natsURL: ENC[AES256_GCM,data:8q6q5+mjh2oRMaAvym5xUg==,iv:BExMS7K7AOa/p3ENMlMXm3hXWhJVnQp6/gqHTSLcMvQ=,tag:UBTCjs9hNgEbhlb2y5pRhg==,type:str]
        lineSubject: ENC[AES256_GCM,data:0SgK3AayKHD72v9hJ4t1oLGkgrU=,iv:LBaldiA0U5CRV+Jw5KY4gfuLhww3fXBTz4rH6DyfK6c=,tag:5mamg0PskK2T/W+TNwSdCQ==,type:str]
        discordSubject: ENC[AES256_GCM,data:KH8CzR0Wa8fNyppOA3KhQfJcYHxjRPpBCA==,iv:YOjZSrILsjrAAROUK3H56LrPp1840q0h/8DTEZt+VWo=,tag:m4EPlWYFunYFVN4siuI+Yw==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:GV/nPQTaAQxu9Lxo66Z51mvJWh6tsONDUmlUEu1PgoLAdgMA5zNF,iv:DK3GFYaloVfINs5R78+lkFBRNtqvdGzq00/rhPNUlqg=,tag:FMuPSz5DG4PrbqoY8e9/RA==,type:str]
            channelToken: ENC[AES256_GCM,data:0Iuf8XlJ45hvHKjGlH/rMw==,iv:6xFH1QNZIV2Yps04n2mUbyFRdeACsfDDh1gDljwB0XQ=,tag:aZVqqlfsE+6En0YmA/zDng==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:pZ67igrFNL+nLb3QLor7YYVczLwIULD6luRazS9lOjCz+n16WNlaZYGtacUZPGO4QHn9CZO5cT8Kq06N3Xa8f6h6iKRTDSNqlVzgpT75/LibbGPist4GpdlMc1ENoho1/NqYOuhZOZIhMKAzYOTsZeoi7OAkLH7JPg==,iv:eHuf2nYlq1d+Fcd02NyLixLgCc78M8Oq+jcuVVtvTbg=,tag:POBtYV0QlRifxFRD55ah1w==,type:str]
            username: ENC[AES256_GCM,data:z65B4Bn6/f0TEQjE3vlUpg==,iv:xbEgxvUVv8SzTIGOfZhQMdBAoRd87qZDFtw7htlxjD4=,tag:n5DwKk0yAAS+ybs/06AqAg==,type:str]
            avatarURL: ""
        ingressTimeout: ENC[AES256_GCM,data:bIc=,iv:qmRW8ZW/k6euDBWcakY6TRFxv0KP3xj9CDzVkupNHJk=,tag:s21MwwElZVSUu+UhHtt/uQ==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:2eo=,iv:1sgU43qIdLZlMUdz4ewvvlworrj2v7q9e/Wmvcq0aDU=,tag:sa2yP9p0xmc28Db7ldWpew==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsekI3cDJJaWc1enY3bktF
            MC9mTHN1SkpHWlAxZmFtcUNYeCtDOEtYTXljCkF5bTFoS1ZZaGh2MldPYk1NcWJF
            c1FSSWFBU3JMU053dTh0NmVTN0p6OEkKLS0tIHcxN2dNZW1scU9SbXBmWEo4Tzcr
            VER0dUVxMnV0K2liYkJqYzFkbERzRlUKUk1mCzRoSd7YuScE3aXRMenBUJI0mM65
            xIbbQlRsvextsuqdaRkmS92WUQbkwHkFF1TyyoSc2ZAebz+ZfSkV8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:35:25Z"
    mac: ENC[AES256_GCM,data:KoZ/Vly8IWa1NdRdf1A3qMWlJtVNn0uJy1AMu5A9Ch+j4FhMS/bXN3+Qx1mMmihOtWElJ/UPT/tns2yfk91V6SJE/sJVIfDaB+RqJK258VImGD3U2pW32Yij23zRawPeYvXe/aNjrY8ipSAapXj7D8UK8mxngozwvP12anu4JR8=,iv:MU5Y9TpZrHXry9oq30D1+/tWQmX0D7f8U2V+vv4mChY=,tag:Sdmp26CWoJJGWmjAKaSNdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
