auth:
    example:
        allowedOrigins:
            - ENC[AES256_GCM,data:YECoyFqFDNLsm1dQTUJ7OJ/0WRsCv/k=,iv:1VTMyOuFHxvBq3YVRwEed5bYJqvqU49kIMsKPLkKolc=,tag:t9AZJTDYlEJWgpfUorTymQ==,type:str]
        defaultRedirectOrigin: ENC[AES256_GCM,data:cZVjQm4IMLv1bc7TKqUQLJejmjM8wD4=,iv:MAJo/Iu7H2g+tMDk29Zz+Ac/hCkaP3MnzJCwl2dyim0=,tag:Ktrp03oIgHN8pkiqbtCO/g==,type:str]
        redirectPath: ENC[AES256_GCM,data:nV/KzrVier9kTD8t,iv:UVJDZF6Yc6rqn68Ka0XmtnVTV/WNlcJ5IFAciv1C9ik=,tag:Mcyj2NznXBCmZ06GeqyV7A==,type:str]
        line:
            channelID: ENC[AES256_GCM,data:yNtRDY10P2PVF4CpSl5NIY3L7A==,iv:mdoE00UQSiocnRic0GjGcIB2rLVuTL6XqjT5I30/cM8=,tag:b4QoqNf4rbkS/qziifqspA==,type:str]
            channelSecret: ENC[AES256_GCM,data:t2gRpOXiA3nA0fB7A6GCiPIP,iv:sr1cUCBrdKC3TT/g9JETBOetNKq6GxBlFL4zb34KGC8=,tag:HF70aRu7HJ5+ZpOugJ6TOA==,type:str]
            redirectURI: ENC[AES256_GCM,data:ykv0Ci0hOfMaUh1Zo2JBVE4uwmakLyMJHqhlz6EuUiYeHZZ663/Qu+z7,iv:9YyQmFQLfRcoA/cjso1CZaRIrXI2s8/fxDMK7Q5ryi8=,tag:iOc9Qd6t6OLKjImKGqbuwg==,type:str]
            scopes:
                - ENC[AES256_GCM,data:w5Rf4o1V1Q==,iv:huL4ynb4h00tXTYS+WrV6sU2lrjOI/6u67ouyKEMK/A=,tag:aarfI2Va+odook3+GZ6D5g==,type:str]
                - ENC[AES256_GCM,data://JTGwcJ,iv:+NQJWZeuDJZgsVjUSUkXMxCNDETxVEs7qb+ScxZNs28=,tag:u69lnD29+kObjPRFe2ER3g==,type:str]
            stateSecret: ENC[AES256_GCM,data:zDHZnFrcampQo9Ap5ewb/DzxRu2AVdDe,iv:fGv7JSBtKTPjURMTYoIu6ZeQzYBbmKqRDNv00i7NvOk=,tag:GnvvRm9A1QNvY2grARflkA==,type:str]
            stateTTL: ENC[AES256_GCM,data:QPHo,iv:FoXrfYspvwNnwVmb3nipamShPcB8SGB/RG8B7PdBOKg=,tag:YlmaDi5UhHOdMCVCjSXeYQ==,type:str]
            jwtSecret: ENC[AES256_GCM,data:BqiRwkduq2cgxJOK6LoTxOoMZL4oqA==,iv:FxFJByK2Qg9oDOV0EBn3r0xYcpskOaKRh9EIG2KnIwE=,tag:DRPEUiIebgInNO7aNiF4HA==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:h7OYls4LfGXC,iv:XgZd+0R3+rLEh9jxK8u3roFdOo2u6p7ctC2Tx3nQ+to=,tag:MMbZW/dphP8owIdY20J06w==,type:str]
            jwtAudience: ENC[AES256_GCM,data:CcT5q0PkxA==,iv:KY75Nqfsw4pr0kg77FCn+dpB5pcBW+YYpg+FvMLUSBk=,tag:dQOuAkzfEJOPmj2varqx0g==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:3XgW,iv:UHUedNcAaS86qITIBqGEcHOHsdGOLtWSN36NnZ3A2AU=,tag:xwHdMHCzDiXc8YuAwCslvA==,type:str]
        twitter:
            clientID: ENC[AES256_GCM,data:9j1X+/JTHvFc5LkQEjsauSiNZPqD,iv:xu97RhRUGQ1vMgzfC201aeUMh+pK99+JgzqNuJXURaE=,tag:vnX6fJmKCvmvvmMWEUbiuA==,type:str]
            clientSecret: ENC[AES256_GCM,data:9Rm3v0fNm68pdIbBwgvEVKzDtAS1,iv:EU38JUmg6DDtJDwhyPeVF5PrqDjB+t8lRj6P9nWkTO8=,tag:n6/jmJX32T8m8u/ePiZCpg==,type:str]
            redirectURI: ENC[AES256_GCM,data:mgE7ofVAxzZZAXSyHakEGqlLiCP6SUxyfKAPxrvxHc6lGmiZJ9Z1faa6IdrH,iv:gEEM9oYkG1mMdQAUlenY3DTuKa8CMy6IfiS8SaszWn0=,tag:6yYUBKrgqQ9/GLNU3vUIGw==,type:str]
            scopes:
                - ENC[AES256_GCM,data:WS0vb2ofp58CGA==,iv:k5jk8eNsn1c+iOL4m8VSyMnXRAlYEp0zBIEuoNJGYNs=,tag:6if3vUQH1c+CW0972I+9kQ==,type:str]
            stateSecret: ENC[AES256_GCM,data:fe1AuZz5+T8KBrTJH4v3OfPEFia/S/6bG8i+,iv:ssdfiCGpb4W9mpWbQmqnzGxhlCoC2thXFd/IRQ9358o=,tag:EujIHIzj0m4v4AxEcWMXaw==,type:str]
            stateTTL: ENC[AES256_GCM,data:Cz9D,iv:PxKP1QYsjZ/T0ajgBb01u/JKiE8nMYiMZ1HzqTEWicY=,tag:2EzT8+vlTT1ZsO+A4uiFsQ==,type:str]
            jwtSecret: ENC[AES256_GCM,data:AodaKxFMxLBihAI2DVlkvkuyxs6u8kJJ7g==,iv:Inm+B8jUfqA/YS94NH9mLguVVThMacs9uUMe3SYZtoE=,tag:pyb1nuA9Gi91v9OTUqn09A==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:O77K0hOhQmlxR/dE,iv:oUKMHff3tLf8IEPzo0+eBXjgtQzoTYBYbgErey3PqVA=,tag:m8rZO17r+DMXp2fQnJ6UZw==,type:str]
            jwtAudience: ENC[AES256_GCM,data:nQm4XasbXg==,iv:jnhDpOgI0PbfgMw1y8n24OmSvLVK6Q5YfoPlzXIKipM=,tag:JpOaCU+8LZr9YB3VCmotIw==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:vQn+,iv:sgslc6lDekc/AmVCGKOplTAlpXLEDT0Cqj49dF9P29U=,tag:++4tu4AR6cslBkjlSm82oQ==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVE9UOXc1M1hiQStCT3FP
            WHhteVM4ckJ3bzI0Ty9NQTNGWTJIanVjdjFzCnV3NS9WcklDV1o4WUFPc2FnVWFu
            SW9pcjB1RGFzODdJV0N3Y3JYb1BWL0kKLS0tIEIvR2Z2Qk9jbGZSOHpOR0RPbDkv
            dFhOTS9FL1NvQnNNZXFMbkdRRDdGTlUKH6Y7BbTIif3lRJhcOnywK8vlvZicXXUD
            feigz0kxHGWXrZapN7oRQLdmFvj8WPbJwyg2iwKwJesiOepJE5orUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:35:25Z"
    mac: ENC[AES256_GCM,data:M89xi1YspTVzWxz08TOvWYQku7Y3sg6I8SjQ2KmcWN/zfGdz832xdrJIjO6AphDDkmDvWGxeSA2Ti8l/qhibW3CSak6BqRF6ykASFCJ2vObYDucKHTOA9N3mK+ne1FYKnlQo+8Xt53Q2yz+xJzB4CsyDS1zMEKlqv9ObMemKP+I=,iv:a0UaSsqSiUdU/arg7NNV74uJ3R2317M0ARfVdMdvWCM=,tag:Dnj189Zy9+dMIz45VO56Kg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
