auth:
    example:
        allowedOrigins:
            - ENC[AES256_GCM,data:77YCjyujB0XzVGYXt3tRuWdNJVWZjX4=,iv:zM5i0JG1s4z3vZ0DzLXkj+YF1pkelxr3sz4PTZp/aUo=,tag:vP0r9qwXyyRLEEGq2ZCINA==,type:str]
        defaultRedirectOrigin: ENC[AES256_GCM,data:Q/vq4ib6aB6Sbb0JMer3a/lqX0H/IXU=,iv:p823Luw2Yqn8Kuea7zJ6UXvm1r6PnRdMQLnOihtPy5c=,tag:9y/hz90nxYvHAnMbqF+YgQ==,type:str]
        redirectPath: ENC[AES256_GCM,data:tc2BLOe8UnySfohR,iv:9EkAKpsWzKGYGVbHpwGIFO6AhS6aPsNSAUU/ZP25QHI=,tag:znCWTrnhceiuqgEsFb4noQ==,type:str]
        line:
            channelID: ENC[AES256_GCM,data:fJDmMhZYcLRs0/2/1lZjZ/WK9g==,iv:ZUcaQ0JOKxhJWRTQCZij8W3pY4H3zMW+S9FBnwl9GAo=,tag:4tHbzsYj+6UWaMpZAffi3A==,type:str]
            channelSecret: ENC[AES256_GCM,data:IHu0d/agYRyfEDZwMnAMwh+2,iv:Agl47HCCzvz0VQrRSXcYCTSAwJJEn6d3D3M0fIbhgSQ=,tag:R+HLfJqqCWzS5gtv8KzVgg==,type:str]
            redirectURI: ENC[AES256_GCM,data:AUPRy5HXOqgpir2pMO5sY2B2DTEU5jhASXGIjacK3uoUGcDXUAVozSKX,iv:yGE6iKhcx/xT13ifRB33StlSHoro29+qT6/zFmvJ5nQ=,tag:f2ClMUOCYhgi1J7WrjNlnw==,type:str]
            scopes:
                - ENC[AES256_GCM,data:btrb682WWg==,iv:CSyfsifxdJAnUbVttmaQzybpkfBa5VhASRNB4eosKJE=,tag:JjPwifqFCzxpCZA1v9sr7Q==,type:str]
                - ENC[AES256_GCM,data:RbTsuFQa,iv:7p/6WuWv/ZtyxQLGW0r/Qm1XMi6JQJSItC8VMu6dg/w=,tag:dA7dv1CgaG0MBQvL9Cfo3g==,type:str]
            stateSecret: ENC[AES256_GCM,data:qW0EBJYmbUzRMPJgmwQJHdd2TLXw9CwJ,iv:OP3+HRgihi3Bj09dcI0xYlEAxs/rU7jgxTIKeG3HG/Y=,tag:47758KDAPns0TTO0ij7l6w==,type:str]
            stateTTL: ENC[AES256_GCM,data:+gUh,iv:DzDuofeI+ean+ZpHzj5vKG5r6D4aPta/5XuuovvZk2E=,tag:251N7I1AzmdnfmYVgeMjkw==,type:str]
            jwtSecret: ENC[AES256_GCM,data:+XztkQ6OYZ2w+DVFlerZYDus9/KTVg==,iv:cnyEpbYK8PtandVwabMEGc/gcyPK6RSTViSpXPn8bUo=,tag:IXVrCD5q3DtKaZ5MCbevQQ==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:ICLvJX3YbKOL,iv:kX56V9bycYTqO77Ri70DkVUdwvpR3CZhVvV7PG1RhkQ=,tag:dLQ1NnkfikVjB46ouKyCCg==,type:str]
            jwtAudience: ENC[AES256_GCM,data:f5u55yNZYw==,iv:NAXaqy5j9KoVyDIvtoqd5mjs3NdpuR83jHodd6iRzL4=,tag:Ybu+EMi8RSkttxoeo0ohbA==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:M7CE,iv:REQuAa55XHxbRAr4d52CkdZGcFXFl+l94eIPv5PzkGo=,tag:yBtIz0bVcjrjoePLhADpSQ==,type:str]
        twitter:
            clientID: ENC[AES256_GCM,data:K5o3+/MANaa9DZdUMDvdjtWzKySv,iv:z7obW4d1wX+ZlkjzUBm8KKFkBP3caRA0u8+v44xF2Tk=,tag:fZ2zn7Ue13+R6d+SA8vnNQ==,type:str]
            clientSecret: ENC[AES256_GCM,data:usCUAm8CBAXYmWtOt8VZQwY0JQKM,iv:yr2oRIU8ydYQbcnhBjyu05n+OUDlrKB+oLyTwsvHs9Q=,tag:n5l6WIqvjAtEcbuhovJL8A==,type:str]
            redirectURI: ENC[AES256_GCM,data:bG8JEz+jtlw2+tGqt5K0QyVQ8w4pWntcQZZ9poTT6W/64bVkR/Z9Q4cDd7bG,iv:yCwmWEVJnrHz6GBaaOJzlMtXBgW3UBgL35ijerrtg6M=,tag:/t1bMMFDCxbI1tMZjsbQYQ==,type:str]
            scopes:
                - ENC[AES256_GCM,data:SuFLpFu+HhEFvA==,iv:+wOn49yrsvxg+XoO6GHHgWB7linuLmReZYyZa0JkuNU=,tag:lh9frUiWUh/vFfRZ9KtwAg==,type:str]
            stateSecret: ENC[AES256_GCM,data:uLZjSks98gu4oS0cY+S/irG3BWzusnueIyTg,iv:S6b+fFDLRCBeIawTCsSwcVtLz3qoRNPYiifHx+Od9FU=,tag:XOFeL314YWxYcO9rBVtHNA==,type:str]
            stateTTL: ENC[AES256_GCM,data:XNz9,iv:nC8pGR7EDbqL9P11ZG2mkFNR8dP6cBZUoYlINScBc4Y=,tag:nNurbf8tAlBbFir6ehMtIA==,type:str]
            jwtSecret: ENC[AES256_GCM,data:6cOZErw+aRCCpocnU8Y6qOGzIESi4VJHfA==,iv:epMoaVDc8a03dF7J7IA0jG4mP01jAnDPzGhXus7eYKI=,tag:f+U7FG6KQNMigYeTpU8Hmg==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:zDOFqtnGuXe9Wlhe,iv:NXnF5FGfuoSEppmzLMPa7GLDpXiUgfiiSsVE5i3tmdg=,tag:Bog6E0XaUO6V10eQgDMYMA==,type:str]
            jwtAudience: ENC[AES256_GCM,data:LzMXdavKlw==,iv:LZ+sobYVzXRJGn6itl/afKAK1cuedJcyFM5ER3FNc2s=,tag:psCqP8sMDhUW/DRpj9V85A==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:C9+V,iv:jCormbOthxozAIH6crtmM+JbSFlEpqyOLNXAz5/7s60=,tag:mimSFJK755QaCk9O07BU7w==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbXJuWThxbGhza09xdmEy
            L1NDazNlRS9wa1pYOTQwa1FLd0dSREcwRnlRCjdHc0VMT3BZY1pXTEkwZWZycDBE
            Y1h1WGVFZzlKYjB1NTRtM1U4VEFqL1kKLS0tIGdZckZuVjJndldsem9lcWtOTDFU
            dHBxZDlLNC9uZWhCb1VTc0VwMmxwL28K7HHXplSV/brfrTC1luJ5GeeTq8TCdMjw
            Zwq0pxdlpHm9CUMXaRe7KjTyjiaGqgd5BPEGqdcEKWlnW/f4QE1iFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T14:44:16Z"
    mac: ENC[AES256_GCM,data:bmwLuWXuzvzD0eKRwgJhfJ13kg5wTJiW9kefv2k3ZK/CRnlyu6Gnhu14GJiFajIYsp/dBsjW8NeIXrRJirv2Qf3Sltj8XzxueHlofgt343UijX5AXl1hoYcIXDuxzdTVO51tWaEeKcuV7KEe776uitJIHD5EJMezySG197kxMm4=,iv:a0UTfIAQ3KbyUYPB/bgRGn6X53vR3jepwnwU/zPvcdM=,tag:smFyoOgsBDMb+DsGADnmnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
