message:
    sngm3741:
        natsURL: ENC[AES256_GCM,data:RfqXQQacdk9I72OoYl+ggA==,iv:dkXFf5l4fPiP/akd3+q/Ptii8AX1XwkLfdPP/JeKfzc=,tag:NLK5R2OF8FLUzhQJE4oA/w==,type:str]
        lineSubject: ENC[AES256_GCM,data:cBKzTnt/UADdD2fAoW7QrifY1yY=,iv:Cx8HNHxOI/kNpY+PU0A40sx0LglIuSHRcqlKatetrO8=,tag:7qAgz2SR+1Oo0zXBV5s0ug==,type:str]
        discordSubject: ENC[AES256_GCM,data:s960hLbC+CCW63WYttz7522ph17T6tEPUA==,iv:h1lQg3vYKaLoRiZx7aiOK+qVygEfopFbK6cGro5D4lA=,tag:t1yBB4ywYRMOf03LZh0rEQ==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:RIr6md4LOM2PONjAAG4Nsj1Ojo+ZVXCC/NI6fUy1xIqMzQN201zV,iv:D+ErsZrUA2xIfl53ntr5ZEOUyiOr7a8+YXQTfCDT6N0=,tag:s4vHB0+B4CSxNxO3HsZxBw==,type:str]
            channelToken: ENC[AES256_GCM,data:2C1fLXV5VcmmYaTPNGE=,iv:uI716SWYVLBkCl/SeQsXBYe3KyFBiHKjEdQqp1rrZnw=,tag:VFqRA8bXZfR189Bd4dtdvA==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:K1l3OWvOCQOLP25QOyvnXi92rv/2pO7RbdKY2ZUnC8A29lxcczV2JZgqvwP8a0OzjgNpNqk8Ls39Um9s9/6JOu+CIuaEkFoOChEYUUz6229zp97r4D/U8prHIHr2wlLPndCCyjitcE55icVD69+JNc7xSRD07odR4g==,iv:cfEk6QwQYThFo7FhaAJ56huOf6pZjbj+ctzfoguWIlA=,tag:5r8K0AX5sy2P8EPEOK+eEw==,type:str]
            username: ENC[AES256_GCM,data:QUj1Oxv3ybr8suqN0QoHag==,iv:dK9E41y1FlduOlW3Xxce+Hcs9DvUxGkI71iVaPXRpfg=,tag:LYgdPXwiU00QFQ+6cgDWvA==,type:str]
            avatarURL: ""
        ingressTimeout: ENC[AES256_GCM,data:Qss=,iv:n591YwmqfmVcX1L1MtX55LVI+OWmOY8l8O39BGSmBCw=,tag:/ohThq+EAOhAOILDSnxyhQ==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:pNI=,iv:/z1SeZ/eIIx1K3fgly+wl9vIOiwD5ayRBKQHU+2yUe4=,tag:HQ7E90H89+TBqA9Kn+TCjg==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M1hEUGZYMmNrTTBhS2JG
            VTVmelYzeTAzUVFYM0ZNM0JUY0dMQm1TbTM4CkdNVDlpbGpwb1dBcktNNVFyODVs
            RFQycHpidE9lNFk2UVZab0RXRGN0T0EKLS0tIHExcHlSV2ZocHo3ZEJwNjh1eVhH
            c2QzS1FKRkFxS2RiTXVaK2RsN3VEZ1kK4YSxrD32DanDBeX+T5Sgj0pcASsQFXs/
            FKgwnSBb5/7k9o+Sy6nFOn96yNo4BqplOroHoWcZ9fsWWZUaKNZ6rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:35:25Z"
    mac: ENC[AES256_GCM,data:GU747FkshXBIK9UWX4UOaKvgDED5XESFH0NuWEpdf3r8I/IQV17j40JOkg5nbQsR/5fe8sUbvG873Q0tzhvCVrOCefFozGseD5yif1JcpoDhok5DKc4d8Pz7fjhmgXeHT7tk/rtt4MlQ1LnBYZotlveEtkv5tLu1Emw2MsZcLm4=,iv:HNxrsUKmqsHYy1anPVuGehv57jgx6/7XqRsg7pfJdFc=,tag:I50Dbw3bGyxh48ry9mXIuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
