auth:
    prod:
        allowedOrigins:
            - ENC[AES256_GCM,data:qsKwiseG9Ckd4OMEuBMlSmO1SqCrv5c=,iv:7vEPc2I2CB71+O4FnYkrB2LQOP3DtEQ44IbH4fm45Nw=,tag:SeLiw9yvyTo5Y/8XpMrrvw==,type:str]
        defaultRedirectOrigin: ENC[AES256_GCM,data:4L7AUDgR3P/w2sMFkpXX7TjVu5UukAg=,iv:3U/31w0Txt+LundqIs7OVp+zqQRjeZkc4hSnBcPi8rs=,tag:a+5lVk/v501k/LdotCwz3A==,type:str]
        redirectPath: ENC[AES256_GCM,data:49O6z599ZOlB2vyr,iv:FgeWpunKklbCzIUmn7qIefFnKfAEzg/RoA33xFdDyh8=,tag:gkXbZb6UuOi73Z1bYqlGsw==,type:str]
        line:
            channelID: ENC[AES256_GCM,data:OZ0/LZIJAi8saEP9UCLduLE=,iv:pHoFp+C4O41No/YIoUGGIEkZXv8TYyiP75Gt3uRWDnQ=,tag:mco8C2NjzX066sHGK4kg2g==,type:str]
            channelSecret: ENC[AES256_GCM,data:xcmLs+z1Ng2bUEuGmziXKQ==,iv:ssJ/utkFQlvudA+VtX32U/1qM22AdgPmuu9w4XDTixU=,tag:NofC6fKMvINb2mYVIrhl9A==,type:str]
            redirectURI: ENC[AES256_GCM,data:hiQb2RVBWDKFOY2cxAUa3U2+CYndU7GnqQoIF41x6RwplZkTddL6VsAl,iv:40LPVeThW7Et614M5+fRuZcN2BGWFyKSAnc/M1ISdgQ=,tag:qSie8MDmT4IdwfTvknmL8w==,type:str]
            scopes:
                - ENC[AES256_GCM,data:YpX/VrTzvg==,iv:4psKArs3MjeFIU/o8S1pOTDqLrY24WNRN/4MG5a+gH4=,tag:0UEhR00FmjNjwQOkl4swMw==,type:str]
                - ENC[AES256_GCM,data:DbQIh6cI,iv:JM8UjSVVbEqMS8P0ElHL5vRAmgXA2t2A+dK00qqgFDE=,tag:L09cvpUGf8AZ8rPWYAxckQ==,type:str]
            stateSecret: ENC[AES256_GCM,data:2f6pNfiCuT8J4vP8Yf98HlNRCOx5/g==,iv:twuWERdZd4sqHvyzNB36C+GXttKAjcMBsWXcnL5+RrM=,tag:kg5O7Ei3ichVFJjgGqAKUA==,type:str]
            stateTTL: ENC[AES256_GCM,data:Hvv7,iv:X3ZweW7Jb5LSh+Q12n0HQ33yk8l8rWzz6EEslRHQV0A=,tag:MyCyoQYcfkG1R0ubNZ15IA==,type:str]
            jwtSecret: ENC[AES256_GCM,data:LIO0+z2LKPTQrtDvSla9ny2a+mQ=,iv:upePw+wX6zzuhO+Epy6YLdNvp3h3p52hCdoQlz5iGJA=,tag:ok381VXgWDXvdHCMmvjPkw==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:IquJnJZww/V2,iv:zlroSxmi0B6+smzZGAEkIFiwkG6QYhw0a6Nqv5f+FO4=,tag:X4rKGskKYUgmLMq8+qnonQ==,type:str]
            jwtAudience: ENC[AES256_GCM,data:ByEpU9c51H9rzitz,iv:3kz5DjcHa+tjdzRJF3T1nfzeRALL2wC1ZAbRZi7PzAA=,tag:dTpe7+YgrrUKIGv9EZCVCA==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:/4eM,iv:yYIR8Njp7GUDVe26H1lQbc/EfEsK3VxbaIYmzgxZegk=,tag:y7Bldyz5gHLawyQxtcp1Wg==,type:str]
        twitter:
            clientID: ENC[AES256_GCM,data:+5GULM4iAbP47cnE6YcjoOlQoA==,iv:kiTOheBe/eYdR0oFjKoaZEeLoOgA8h8Nl489GuVyjSs=,tag:RiOU1LrnR9gtWsmm4cHK8Q==,type:str]
            clientSecret: ENC[AES256_GCM,data:gWi/aDAyewGxrXDMRcfKZlrKNA==,iv:l3DfTF0yCDvTNpg1P3J6dQNQf/TQbcj9OnN2y+nIhnk=,tag:s8+yPsccIqDlO7JipUHWsw==,type:str]
            redirectURI: ENC[AES256_GCM,data:rKa2VPvY7S9heFK7+lVF9jJCbktddpeDLyCOuw966PQmP331rmTHyXXoI9e9,iv:9twULsa49Ph3pM+QEF0fRVBOC4pQWiigLle1cXkHAU0=,tag:sYkquIpqq5m6qPc4+gwUeg==,type:str]
            scopes:
                - ENC[AES256_GCM,data:wGJ+6+bBczXefw==,iv:9Uayc8fcVZ2p27lhzuMe6JIB7M4VFq/uZk4IJxiNUfU=,tag:f26VWhhBKyKaIh5tE2067w==,type:str]
            stateSecret: ENC[AES256_GCM,data:DJ3lUIIvI4I6F6kxbkGAdhWO9QClJyWy2g==,iv:6lBMidYyF/tTNhB4YCTntOmKtNI9bzQWrCIuiJs64ss=,tag:W9ZIbH+BJ1TWaA+6S2WvgA==,type:str]
            stateTTL: ENC[AES256_GCM,data:cx2w,iv:J5lxOqoCf8wtgfX0Iw90uH5Ujc9lLnA1ZqUhdS9YZaE=,tag:yEwUxVq64HDVrBsJdpMXLA==,type:str]
            jwtSecret: ENC[AES256_GCM,data:JD9CJpm5QnblFm6XXeFnYHHkmTqrdfA=,iv:hAX+YKLpc4pE8xeG35vy9RWWXAxe5KxyDALsAdq9wIw=,tag:7urzY6POGLPxhynx3JFHRA==,type:str]
            jwtIssuer: ENC[AES256_GCM,data:JPxVFZYwE/vhPTOf,iv:qelKtDuVDqbJZ3NZYnE4ZKGq+QFqD+OZTB3UC2XjUxU=,tag:BfjlbwdA7HQ+X1r5PbGSNw==,type:str]
            jwtAudience: ENC[AES256_GCM,data:L5mi3xvuRDxaSO4+,iv:UKO7pKJ3c24Ecyg9GtFQ5D929Zhb9SGzlgIhtaJL7DI=,tag:F7hjZONdVcqCjmocVk2T4A==,type:str]
            jwtExpiresIn: ENC[AES256_GCM,data:ZOxJ,iv:A5hDZl+Rw8JwXt5xnecOisKV0RkP5SFPtKsyiKjw/u4=,tag:BgZe0hfFowwIC8tcph5dOg==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFFpOWo4RmxrNzJNb09p
            bEJMWjV2Qm5hM29VZVJROUY5T2o0NTUrdXdZClU3SllRMTJWdHduNlltMjJqRGNj
            TStMblVqV2s0eDNDSEs0VDRqWUlHcmcKLS0tIFNKMW45bHpTVGtxYmdXL3R0eWE3
            T1Y5N1JRTGwvcXpHeUQ0aGpxUE9tdlUKxfOsrxZuqTeK+SVD4BWuGEceWiN1M+26
            8s6pxa/OoFeeDm30TuE4n838/UpdF8D2fbzZEDlxnan0q5ibeWZbWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:35:25Z"
    mac: ENC[AES256_GCM,data:Ew+es4trrkCj1mSoUmHScQ1M8anY42XkWwd86VLI7UKJvsjAyOvBPtYRB11XhgX5ur9br2/GPuaHXz8lBm5fuYa22k3gEaw0M5Mr9dmLHvto3y8FG6zBTWMz+hvplGYaQnSFLiPpm+yFH57fby7TBbnkBjlIx5RD/HIwLco469Q=,iv:QGbk/V53SLV52hmDwmOEGIpXa+wJKKgwR9E9TChLf7k=,tag:HeSOxCbYKVy8c/FdGUd9Aw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
