message:
    sngm3741:
        natsURL: ENC[AES256_GCM,data:hzB4q5KHADbbNOO2vc/sXQ==,iv:cSE4dKVYl09XnLA9f0jUrZycc0OywV7JXLZlK+jBIis=,tag:aUioASDsVXKZZq5vDCHStg==,type:str]
        lineSubject: ENC[AES256_GCM,data:h7hS5gkBlUsx8aegAZRxgSTGUwE=,iv:L2f0laWSfS6Mus7KtCS3m0BVx6kbiUGSWN8YJaFLHaE=,tag:VRkUvtG27OwlfNSKeJJyaA==,type:str]
        discordSubject: ENC[AES256_GCM,data:pmHJJa+BUP4583/sbKaSmYzz6MREfN/QmA==,iv:EprnZ6Wf7NRRSfJpV26/aOxMkPISzfEBK6YpxevzXXY=,tag:+wVWrtyfMSqULwLFEcUoSw==,type:str]
        line:
            pushEndpoint: ENC[AES256_GCM,data:JZuWODYAksy2bv7rsZvLz5n5i5TfVSXbQlGjVuM5gNsOKXILzUab,iv:toqbX1SZDXrZvDKTczZvO8jb6mq1LBbHrthkx9AgnOc=,tag:3RMW3iCtmGxMCw2QN3h2ZA==,type:str]
            channelToken: ENC[AES256_GCM,data:A9/jdGsT3Kn9cWtH7xlD,iv:wviyaEjehhWsy3qZbBs7cRrvFAt3dMVN4LO0bnmvtEg=,tag:4xz8J4rFOADKaS4rJdcvKA==,type:str]
        discord:
            webhookURL: ENC[AES256_GCM,data:N/xzX/uS94OebWAhamOcKM7WMnNPHDZQIeLlt4OQ/WmiKiGVjBnrAmAnEs0a/k3lrj7aDqVUlUpiiuKSxZAHDyOUDE7zHUdcrWTiA9H4i2Htq65mMH0DkImOI+dQ704SDmoXennEK6DXim75RWa6EfQJSEqgW2/WHw==,iv:TSaNDgbBfQWqS97mlCpZ/qeOO8TnkLZndLDobYCsKWc=,tag:cYOXmJTH5we2OMrcplIfSw==,type:str]
            username: ENC[AES256_GCM,data:D2WiDlnQUI6AcZ9eEZFzBg==,iv:ukrmYEOKDyZND98ZfdxOmNNY+37nEuRSfB/mj+JD9EU=,tag:vjclvgAVWGVDdwoZs9QOzQ==,type:str]
            avatarURL: ""
        ingressTimeout: ENC[AES256_GCM,data:BJQ=,iv:MZRKebevqY5khV+598hS9UGrX2t7Qxf+vyJPlyUylyc=,tag:ZhqYrDVi28FxIKrA1UwBLw==,type:str]
        workerHTTPTimeout: ENC[AES256_GCM,data:/dU=,iv:6E9u+ezo49PqeIcrQmSB4pq9vjhYps5QqZrBR4L0y90=,tag:xOZ30HqIV7Maxx4KrnE3yw==,type:str]
sops:
    age:
        - recipient: age10ylnv6zweltf3jeme355vt07myhree04445cxx8mpg59w880ycwqp44fhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NFN4WHRzbzgwNXE4WXRK
            aUlJOVM3ZHcrdHdqaTI4anYzcnZicDNFSW5rCjdGUlN3dEJYbmJSWmpnNGtTMjgr
            REJIYmpKRTNpV29QdklOWlAya3BjTkUKLS0tIGdXWXJSakZrT3k4U01qNzZtZmdS
            aGhwNXBEOUNOWEt0a3FCZG50TEsxSWsKs38ouvXkhMjKbvHTapp5k4HG9glpktux
            MuB3c7ftj/TRwDZ/OIXjasdWAjmh+mUvIM9V5BNICMG4BcpzP4bxCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T16:35:25Z"
    mac: ENC[AES256_GCM,data:ZJqNY/Mah3JOu8L/vdxhRKerkKlVgpzFB7lZn2f4BDgU2K8dJ65OftffRBcMhscgHciIcCmIT0jrZ7XQQbr1ff3XtKzc1kCjQEDHaN46F91v9kfYGA+DtmXTcl6enSbHlTknoRbmbz3Gvea/MYfXMwAFLgAtTa56hzibvXkA8qc=,iv:oy6NDW7Ado9vqhH8ZX6iGXdeBp+dR1BaAwb6/fGvks0=,tag:xtAXXe/fH3LwYf3GAiLa8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
