name = "makotoclub-admin"
compatibility_date = "2025-02-07"
compatibility_flags = ["nodejs_compat"]

# Pages 用：ビルド成果物
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "makotoclub"
database_id = "13a8135d-e968-458b-986b-b6047f2c859f"

[[r2_buckets]]
binding = "makotoclub_assets"
bucket_name = "makotoclub-assets"
